development:
  adapter: postgresql
  database: colabo_lei_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: colabo_lei_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: colabo_lei_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0