development:
  adapter: postgresql
  database: colabolei_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: colabolei_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: colabolei_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0